### PR TITLE
Test jupytext master. 

### PR DESCRIPTION
**Pull request by grst**
This is a test if the conda ci can be triggered from the jupytext master branch. 

DON'T MERGE!!

### CODE REVIEW

**Comment by grst** [comment]
@mwouts, 

this PR builds directly from the jupytext master and fails with the same error message.
Thir PR could, therefore, be abused to test the conda build before releasing a new version (closing and re-opening the PR will trigger a CI build). 

I don't know if there is a more elegant way, but this would be one option. 

Cheers, 
Gregor

**Comment by mwouts** [comment]
Awesome! Thank you Gregor.

**Comment by mwouts** [comment]
Awesome! It worked. Thank you a lot @grst . I'll close this and reopen the next time I have a doubt on the build.

**Comment by mwouts** [comment]
Reopened in order to test v1.2.4

**Pull request closed without merging**
