### PR TITLE
use github url to get the latest package

### PR DESCRIPTION
**Pull request by bgruening**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bgruening** [comment]
@conda-forge-admin please rerender

**Comment by bgruening** [comment]
@mwouts it seems the pypi package is missing. You might want to upload it. Until then I hope that change is ok.
The .3 version is breaking atm a few deployments, so I think its a bit urgent to get this package shipped.

**Comment by bgruening** [comment]
:(

>   ValueError: Aborting. Could not find cmd (jlpm) in path. If command is not expected to be in user's path, use an absolute path.

**Comment by bgruening** [comment]
@conda-forge-admin please rerender

**Comment by mwouts** [comment]
> @mwouts it seems the pypi package is missing. You might want to upload it. Until then I hope that change is ok. The .3 version is breaking atm a few deployments, so I think its a bit urgent to get this package shipped.

Hi @bgruening , sorry about this, yes my publish action was failing - I've fixed it with https://github.com/mwouts/jupytext/pull/1265/commits/60e18e27b48d3336c08db0de83a05362af0c27fd and `jupytext==1.16.4` finally made it to pypi. Thanks for the fix in the meantime!

**Pull request merged**
