### PR TITLE
Version 1.10.1

### PR DESCRIPTION
**Pull request by mwouts**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mwouts** [comment]
@conda-forge-admin, please rerender

**Comment by mwouts** [comment]
I am not sure what has gone wrong here... In the `.tar.gz` file on pypi I see the notebook extension, but according to the tests it [is missing](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=276455&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=883) in the (candidate) conda package.

Maybe this is caused by the removal of `graft packages` at https://github.com/mwouts/jupytext/commit/6abaea016a7239d685b958ab0cf9b944bde902cc ? I'll try to add it back.

**Comment by mwouts** [comment]
Oh no, if I add `graft packages` back to the `MANIFEST.in` file then the `.tar.gz` package becomes huge again (45MB) when built locally with
```
BUILD_JUPYTERLAB_EXTENSION=1 python setup.py sdist bdist_wheel
```

@martinRenou I am afraid I'm going to need your help here once more if you don't mind :bow:

**Comment by martinRenou** [comment]
I suppose you need to include everything that is in packages except node_modules

**Comment by mwouts** [comment]
As appeared on the tests above, the `.tar.gz` package for Jupytext v1.10.1 was missing the notebook and lab extensions. This should be OK in v1.10.2 thanks to https://github.com/mwouts/jupytext/pull/741 (so there won't be a v1.10.1 on conda-forge).

**Pull request closed without merging**
